version: '3'
services: 
  app:
    restart: always
    build:
      context: .
    volumes:
      - ./app/:/app/
    container_name: app
    ports:
      - 8083:8081
    network_mode: bridge

volumes:
  app:

